### PR TITLE
Mir 0.3.1

### PR DESCRIPTION
**Pull request by dnkolegov**
This PR updates the version of Mir and switches to the new Mir's mempool.

@adlrocha please approve removing [that](https://github.com/consensus-shipyard/lotus/pull/115/files#diff-e8508e0e40cf886053ceaceb14a631a3f7eb9d19468d36aa6e4b261c1f355d9bL254) line.

### CODE REVIEW

**Comment by matejpavlovic** [comment]
1. I [generalized the Mir mempool](https://github.com/matejpavlovic/mir/tree/generalize-mempool) to make things much simpler. I factored out the fetching of transactions to one function that you can supply at configuration. This way, no separate Eudico-based mempool is needed, only the Mir mempool needs to be configured with a proper transaction-supplying function.
2. The new Mir version, as we discussed and as is written in the [release notes](https://github.com/filecoin-project/mir/releases/tag/v0.3.0), explicitly announces a checkpoint even if state has just been restored from the very same checkpoint. Thus, [delivering the checkpoint to Eudico on state restoration](https://github.com/consensus-shipyard/lotus/blob/8b571bc6689b2b51532d7dcf442aac5054bf5a7f/chain/consensus/mir/state_manager.go#L251-L257) is now redundant and most likely breaks the integration code.

**Comment by matejpavlovic** [comment]
I [fixed] the bug in the [generalized the Mir mempool](https://github.com/matejpavlovic/mir/tree/generalize-mempool) code. I hope it will now work with the updated version. Please try.

**Review by matejpavlovic — APPROVED** [review]
LGTM! 👍 
I still think that constructing a whole Fetcher object and passing its method to the mempool configuration is unnecessarily complicated, because we could just use a simple (even anonymous) function. But it's definitely not critical and we can pick it up later.

**Comment by adlrocha** [comment]
> @adlrocha please approve removing [that](https://github.com/consensus-shipyard/lotus/pull/115/files#diff-e8508e0e40cf886053ceaceb14a631a3f7eb9d19468d36aa6e4b261c1f355d9bL254) line.

I am afraid I can not make a call here without looking deeper into the code and the latest changes in Mir. The reason of that line was that when we restored state from Mir to catch up a peer, we cleaned all the checkpoints pending in the checkpoint channel, and as checkpoints are attached to the next block after they are created, we had to deliver the checkpoint from which we restored to the channel so it could be included in the next block.

I don't know if this is necessary anymore. I trust your call (unless you want me to look deeper into it). Thanks.

**Comment by dnkolegov** [comment]
> > @adlrocha please approve removing [that](https://github.com/consensus-shipyard/lotus/pull/115/files#diff-e8508e0e40cf886053ceaceb14a631a3f7eb9d19468d36aa6e4b261c1f355d9bL254) line.
> 
> I am afraid I can not make a call here without looking deeper into the code and the latest changes in Mir. The reason of that line was that when we restored state from Mir to catch up a peer, we cleaned all the checkpoints pending in the checkpoint channel, and as checkpoints are attached to the next block after they are created, we had to deliver the checkpoint from which we restored to the channel so it could be included in the next block.
> 
> I don't know if this is necessary anymore. I trust your call (unless you want me to look deeper into it). Thanks.

@matejpavlovic @adlrocha I would suggest discussing the changes in Mir to be sure that all are on the same page and then merge.

**Pull request merged**
