### PR TITLE
Reduce initial funds to test address

### PR DESCRIPTION
**Pull request by adlrocha**
This PR is an excuse to open a quick discussion. So far, before we had cross-net messages, we provided some genesis funds to our test address to help with testing. We were funding the address with 5000FIL from genesis. Now that we have cross-net messages (and considering that the wallet key can be potentially leaked easily as is the one we are using for tests and in many tutorials). Should we reduce (or completely remove) these genesis funds even if that makes testing a bit harder for us as we would have to get funds from the faucet also? (practically we could also fund some other address manually with "significant" faucet funds).

This PR reduces the initial funds to 50FIL, should we reduce it more, leave it as-is, or remove them all the way?

### CODE REVIEW

**Comment by dnkolegov** [comment]
If we can, we should remove the funds!

**Comment by jsoares** [comment]
What I'm hearing is that this address `t1cp4q4lqsdhob23ysywffg2tvbmar5cshia4rweq` is initialised with 5000 FIL both in the local root deployment and in Spacenet, and the key is in https://github.com/consensus-shipyard/lotus/blob/f5c0d77e7edbda1363b121c553dc7ac53a824b45/scripts/ipc/src/wallet.key. And you're proposing lowering or removing it in both. Is that right?

If I understand correctly, that's also why https://github.com/consensus-shipyard/ipc-agent/pull/167#discussion_r1170699893 happens. I thought this was only a problem for spacenet initially and that having 0 or 50 was indifferent, but now I'm thinking we should bring it to 0 to avoid these inconsistencies.

How does this affect local root testing, in the absence of a faucet? I guess the rootnet validator should be earning FIL that could then be transferred but mine doesn't seem to -- despite everything else working fine and there clearly being validation taking place 🤔

**Comment by jsoares** [comment]
lgtm but the tests are still failing due to insufficient funds; is this something we need to address or are we fine to release for spacenet and then adjust?

**Comment by adlrocha** [comment]
> lgtm but the tests are still failing due to insufficient funds; is this something we need to address or are we fine to release for spacenet and then adjust?

It was failing because I introduced an unexpected bug :) Already fixed. Thank you for flagging.

**Pull request merged**
